#!/usr/bin/env php
<?php

use iboxs\App;

require __DIR__ . '/../../vendor/autoload.php';

$app = new App(__DIR__);

$app->console->addCommands([\iboxs\swoole\command\Server::class]);

$app->console->run();
